### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by nghuixin** [nghuixin/video_dl_visual_language#1]
- [ ] Create slider for selecting animated infographics excerpts

- [ ] Utilize  ```youtube dl``` for downloading videos from Youtube

- [ ] Exploratory analysis of video data ```finalCSV.xlsx``` provided by Alan
